### ISSUE TITLE
Conteudo .css

### ISSUE THREAD

**Issue by githubwanderson** [digitalinnovationone/semana-frontend-mundo-invertido#4]
Olá Dio.
Por gentileza não encontrei o conteudo css que a Michele desenvolveu...

**Comment by RuanAragao** [comment]
> Olá Dio. Por gentileza não encontrei o conteudo css que a Michele desenvolveu...

Na página inicial do projeto você clica no seletor de _branches/tags_ (1) e selecione a _branch_ "**feature/projeto-completo**" (2)

![image](https://user-images.githubusercontent.com/1015013/186569913-fa020194-937a-4a00-873b-888f8cf52284.png)

**Comment by githubwanderson** [comment]
Obrigado @RuanAragao
